[240214-240215] day1
f-lab-edu/til-algorithm pull request #1
Opened 2024-02-15 09:32 UTC by ekdls1218

2024-02-22 08:44 UTC, f-lab-jake requested changes

2024-02-22 08:44 UTC, f-lab-jake commented on week2/Lv0_숫자비교하기.ts
> +  return -1;
자체적인 일관성을 가져야합니다. 다른 경우엔 이때 3항 연산자를 쓰셧더라고요?

2024-02-22 08:44 UTC, f-lab-jake commented on week2/Lv1_나머지가1이되는수찾기.ts
> +  while (x++) {
이 조건문은 무슨의미죠?

2024-02-22 08:44 UTC, f-lab-jake commented on week2/Lv1_나머지가1이되는수찾기.ts
> +  return x;
이 코드는 무슨 의도죠?

2024-02-22 08:44 UTC, f-lab-jake commented on week2/Lv1_평균구하기.ts
> +    })
요거에 해당하는 lodash 함수가 있을거 같지 않나요?

2024-02-22 08:44 UTC, f-lab-jake commented on week2/Lv2_JadenCase문자열만들기.ts
> +    });
`forEach`가 최선일까요?

2024-02-26 11:09 UTC, ekdls1218 commented on week2/Lv1_나머지가1이되는수찾기.ts
> +  while (x++) {
반복문을 돌 때마다 x를 증가시키도록 한 것인데 다시 생각해보니 while문은 조건이 참,거짓인지 판단하고 실행하는 반복문으로 반복 횟수가 정해져 있지 않을 때 쓰이므로 증가 연산자를 조건으로 쓰는 것도 맞지 않고, n까지 반복 횟수가 정해져 있어 for문으로 바꿔야 할 것 같습니다..!

2024-02-26 11:12 UTC, ekdls1218 commented on week2/Lv1_나머지가1이되는수찾기.ts
> +  return x;
리턴 타입을 number로 설정하여서 return x; 가 없으면 아래와 같은 에러가 떠서 추가해주었습니다.
 `Function lacks ending return statement and return type does not include 'undefined'.ts(2366)`

2024-02-26 11:12 UTC, ekdls1218 commented on week2/Lv1_평균구하기.ts
> +    })
넵! _.sum()으로 수정하였습니다!

2024-02-26 11:13 UTC, ekdls1218 commented on week2/Lv2_JadenCase문자열만들기.ts
> +    });
반환 값을 주는 `map`으로 수정하였습니다

2024-02-26 11:24 UTC, ekdls1218 commented on week2/Lv0_숫자비교하기.ts
> +  return -1;
넵 삼항 연산자로 통일하였습니다!

2024-02-26 15:37 UTC, f-lab-jake requested changes

2024-02-26 15:37 UTC, f-lab-jake commented on week2/Lv1_나머지가1이되는수찾기.ts
> +  return x;
왜 저런 에러가 떴고 `return x`가 왜 해결책이 되는지 이해했나요?

2024-02-26 15:37 UTC, f-lab-jake commented on week2/Lv1_약수의합.ts
> +      }
이 조건문은 최대 1번만 참입니다.
그런데도 매번 확인하는건 비효율적이죠?

2024-04-01 17:10 UTC, ekdls1218 commented on week2/Lv1_약수의합.ts
> +      }
수정하였습니다!

2024-04-01 17:12 UTC, ekdls1218 commented on week2/Lv1_약수의합.ts
> +  }
약수를 배열에 다 넣은 후 제곱 수일 때 배열에서 제곱근을 하나 빼는 코드로 변경하였습니다!

2024-04-02 01:57 UTC, f-lab-jake requested changes

2024-04-02 01:57 UTC, f-lab-jake commented on week2/Lv1_약수의합.ts
> +    sqrtArray.splice(sqrtArray.indexOf(sqrtNum), 1);
넣었다가 다시 빼는걸 피하세요

2024-04-11 11:37 UTC, ekdls1218 commented on week2/Lv1_약수의합.ts
> +  }
for문 범위를 수정하고 이후에 제곱수일 때 제곱근을 넣어주는 것으로 코드를 수정하였습니다.

2024-04-12 02:19 UTC, f-lab-jake approved these changes

2024-05-29 03:25 UTC, f-lab-jake approved these changes

2024-05-29 03:25 UTC, f-lab-jake commented on week2/Lv0_짝수의합.ts
> +  const evenArray = _.range(2, n, 2);
`evens` 정도가 좋습니다.

2024-07-09 21:45 UTC, ekdls1218 commented on week2/Lv0_짝수의합.ts
> +  const evenArray = _.range(2, n, 2);
넵!

2024-07-09 21:45 UTC, merged