[240325 - 240326] 알고리즘 문제 풀이
f-lab-edu/til-algorithm pull request #13
Opened 2024-03-26 12:34 UTC by ekdls1218

2024-03-28 11:59 UTC, f-lab-jake requested changes

2024-03-28 11:59 UTC, f-lab-jake commented on week8/고득점kit_정렬_k번째수.ts
> +    const k = numArr[2];
destructuring을 활용하세요

2024-03-28 11:59 UTC, f-lab-jake commented on week8/Lv2_다음큰숫자.ts
> +  }
중복을 제거하세요

2024-05-15 04:00 UTC, ekdls1218 commented on week8/고득점kit_정렬_k번째수.ts
> +    const k = numArr[2];
`const [i, j, k] = numArr;` 변경하였습니다!

2024-05-15 04:02 UTC, ekdls1218 commented on week8/Lv2_다음큰숫자.ts
> +  }
`n.toString(2).match(/1/g)?.length` 2진수로 바꿔 1의 개수를 세는 코드를 함수로 바꿔서 중복을 줄였습니다!
```
const countOne = (num: number) => {
    return num.toString(2).match(/1/g)?.length;
  };
```

2024-05-16 02:27 UTC, f-lab-jake commented on week8/고득점kit_정렬_k번째수.ts
> +    const k = numArr[2];
`numArr`도 제거하세요. 그냥 인자받는곳에서 destructuring하면 됩니다.

2024-06-04 21:45 UTC, ekdls1218 commented on week8/고득점kit_정렬_k번째수.ts
> +  });
`numArr`도 제거하였습니다!

2024-06-07 03:06 UTC, f-lab-jake approved these changes

2024-07-09 21:51 UTC, merged