[240220] 알고리즘 문제 풀이
f-lab-edu/til-algorithm pull request #2
Opened 2024-02-20 14:55 UTC by ekdls1218

2024-02-22 08:40 UTC, f-lab-jake requested changes

2024-02-22 08:40 UTC, f-lab-jake commented on week3/Lv0_문자열뒤집기.ts
> +    let reverse = _.reverse([...my_string]);
let의 사용을 피하세요
eslint autofix가 동작해야합니다

2024-02-22 08:40 UTC, f-lab-jake commented on week3/Lv0_배열원소의길이.ts
> +}
`map`을 굳이 lodash 버전으로 쓸 필욘 없습니다.

2024-02-22 08:40 UTC, f-lab-jake commented on week3/Lv0_최댓값만들기_1.ts
> +  });
왜 arrow function을 안쓴건가요?

2024-02-26 11:44 UTC, ekdls1218 commented on week3/Lv0_최댓값만들기_1.ts
> +  });
앗 이건 제 잘못인데 `sort()`메서드를 찾아보면서 문서에 나와있던대로 썼습니다..  arrow function이 더 간결해 보이니 수정하는 게 좋을 것 같습니다..

2024-02-26 15:37 UTC, f-lab-jake approved these changes

2024-07-09 21:46 UTC, merged