[240221] 알고리즘 문제 풀이
f-lab-edu/til-algorithm pull request #3
Opened 2024-02-27 07:30 UTC by ekdls1218

2024-02-27 12:54 UTC, f-lab-jake requested changes

2024-02-27 12:54 UTC, f-lab-jake commented on week3/Lv1_자릿수더하기.ts
> +  return [...stringN].reduce((arr, cur) => (arr += Number(cur)), 0);
왜 `+=`를 사용했나요?

2024-03-07 04:52 UTC, f-lab-jake approved these changes

2024-03-07 04:52 UTC, f-lab-jake approved these changes

2024-04-01 17:56 UTC, ekdls1218 commented on week3/Lv1_자릿수더하기.ts
> +  return [...stringN].reduce((arr, cur) => (arr += Number(cur)), 0);
`arr`은 누적 값이므로 `+=`를 안 써도 되는데 전에는 `reduce`로 합을 구하는 방법을 찾아볼 때 `+=`로 써져있어서 따라쓰느라 썼던 것 같습니다.. 수정하였습니다!

2024-04-01 17:56 UTC, ekdls1218 commented on week3/Lv1_정수제곱근판별.ts
> +  return Number.isInteger(Math.sqrt(n)) ? Math.pow(Math.sqrt(n) + 1, 2) : -1;
넵 따로 변수로 빼두었습니다!

2024-04-01 17:56 UTC, ekdls1218 commented on week3/Lv1_자연수뒤집어배열로만들기.ts
> +  return [...stringN].reverse().map((element) => Number(element));
넵 수정하였습니다

2024-04-02 01:58 UTC, f-lab-jake approved these changes

2024-07-09 21:47 UTC, merged