[240307] 알고리즘 문제 풀이
f-lab-edu/til-algorithm pull request #6
Opened 2024-03-07 14:59 UTC by ekdls1218

- Lv0_모음제거
  - vowels는 문자열이랑 배열 중 무엇으로 할당해 주는 것이 나을까요? 

- Lv0_삼각형의 완성 조건
  - 결과를 확인했을 때 맞게 나오는 것 같은데 프로그래머스에서 채점했을 때 틀렸다고 나옵니다..왜 그런 것인가요? 
  - 위쪽 풀이가 lodash를 이용해 푼 것이고 아래 주석 처리 된 것이 프로그래머스에서 채점한 풀이입니다. (프로그래머스에서는 lodash 사용이 불가능하여 이렇게 풀었습니다.)

- Lv0_중앙값 구하기
  - 중앙값의 인덱스를 구할 때 `Math.ceil(array.length / 2) - 1` 와 `Math.floor(array.length / 2)`를  쓸 때 나오는 값은 같지만 배열 인덱스는 0부터 시작하니까 인덱스를 구하는 풀이로는 `Math.ceil(array.length / 2) - 1` 가 좀 더 맞는 것 같아 썼는데 맞을까요?

2024-03-08 01:56 UTC, f-lab-jake requested changes

2024-03-08 01:56 UTC, f-lab-jake commented on week6/Lv0_삼각형의완성조건1.ts
> +function triangle(sides: number[]): number {
같은 길이의 변이 2개가 있는 삼각형의 경우에 오답이 나오지 않나요?

2024-03-08 01:56 UTC, f-lab-jake commented on week6/Lv1_콜라츠추측.ts
> +    }
`count++`의 중복을 제거하세요

2024-03-08 01:57 UTC, f-lab-jake commented
> vowels는 문자열이랑 배열 중 무엇으로 할당해 주는 것이 나을까요

사실 문자열이랑 배열은 거의 비슷한거라서(두개를 구분안하는 언어들도 있습니다), 코드 레벨에서 어느쪽이 더 낫다는 딱히 없습니다.

2024-03-13 05:18 UTC, ekdls1218 commented on week6/Lv0_삼각형의완성조건1.ts
> +function triangle(sides: number[]): number {
앗..가장 긴 변의 길이가 2개일 때 2개 다 배열에서 필터링 해주게 되니까 오답이 나오네요..!

2024-03-13 05:26 UTC, ekdls1218 commented on week6/Lv1_콜라츠추측.ts
> +    }
while 반복문 안에서  조건이 어떻든 한번 돌면 count는 증가시켜줘야 하므로 굳이 각각 조건문 안에서 count++해줄 필요가 없네요..수정하였습니다!

2024-03-14 07:07 UTC, f-lab-jake requested changes

2024-03-14 07:07 UTC, f-lab-jake commented on week6/Lv0_삼각형의완성조건1.ts
> +  const sortArray = _.sortBy(sides);
`sortArray`은 일단 동사죠. 변수이름이 아니고 함수로 써야합니다.
`sortedArray`는 괜찮을까요? 이건 `sides`에서 삼각형의 변의 길이란 의미를 까먹은 변수명입니다.
`sortedSides`로 하던가, 아니면 뭐 `sides2`, `sides$`, 또는 그냥 `sides`를 그대로 쓰는것도 괜찮습니다.

2024-04-01 18:04 UTC, ekdls1218 commented on week6/Lv0_삼각형의완성조건1.ts
> +  const sortArray = _.sortBy(sides);
앗 그렇네요..변수명은 명사로 함수명은 동사로 쓰는 것과 의미를 생각하고 짓는 것에 대해 신경을 못썼던 것 같습니다..!
 `sortedSides`로 수정하였습니다!

2024-04-02 02:00 UTC, f-lab-jake approved these changes

2024-07-09 21:49 UTC, merged