[240309] 알고리즘 문제 풀이
f-lab-edu/til-algorithm pull request #8
Opened 2024-03-10 18:22 UTC by ekdls1218

2024-03-11 01:07 UTC, f-lab-jake requested changes

2024-03-11 01:07 UTC, f-lab-jake commented on week6/Lv0_홀짝구분하기.ts
> +  const n = input % 2 === 0 ? input + " is even" : input + " is odd";
숨겨진 중복을 고쳐보세요

2024-03-13 06:10 UTC, ekdls1218 commented on week6/Lv0_홀짝구분하기.ts
> +  const n = input % 2 === 0 ? input + " is even" : input + " is odd";
삼항 연산자에서 input을 true와 false일 때 중복으로 사용한 것이 맞을까요?
맞다면 고친 코드입니다!
```
const n = input % 2 === 0 ? " is even" :" is odd";
console.log(input + n);
```

2024-03-14 07:09 UTC, f-lab-jake approved these changes

2024-07-09 21:50 UTC, merged