[240310] 알고리즘 문제 풀이
f-lab-edu/til-algorithm pull request #9
Opened 2024-03-10 18:24 UTC by ekdls1218

2024-03-11 01:09 UTC, f-lab-jake requested changes

2024-03-11 01:09 UTC, f-lab-jake commented on week6/Lv1_문자열다루기기본.ts
> +    return [...s].every((str) => Number.isInteger(Number(str)));
여기서 실제로 숫자를 구할필욘없는데 숫자를 구해놓고 맞는지 확인합니다. `Number(str)` 부분 얘깁니다. 그냥 숫자가 맞는지만 확인해보세요.

2024-03-11 01:09 UTC, f-lab-jake commented on week6/Lv1_수박수박수박수박수박수.ts
> +  return word.repeat(n / 2) + word.at(0);
중복을 없애세요

2024-03-11 01:09 UTC, f-lab-jake commented on week6/Lv1_행렬의덧셈.ts
> +}
lodash의 `zip`또는 `zipWith`을 써보세요

2024-03-13 06:35 UTC, ekdls1218 commented on week6/Lv1_문자열다루기기본.ts
> +    return [...s].every((str) => Number.isInteger(Number(str)));
`Number.isInteger()`는 매개변수로 숫자가 들어와도 타입이 Number여야지 true가 나오기 때문에 타입 변환을 해준 것이였는데 제가 잘못 생각한 것 같습니다.. `Number.isInteger()`는 정수 판별에는 유용하지만 문자열 안에 숫자가 있는지 확인하는 것에는 쓰임이 올바르지 않은 것 같습니다. 
그럼 정규식으로 문자열 안에 숫자를 확인하는 것이 제일 나은 방법일까요?

2024-03-13 06:44 UTC, ekdls1218 commented on week6/Lv1_수박수박수박수박수박수.ts
> +  return word.repeat(n / 2) + word.at(0);
`return word.repeat(n / 2) + (n % 2 === 0 ? "" : word.at(0));`
위 코드처럼 중복을 없애는 것이 맞을까요?

2024-03-13 06:54 UTC, ekdls1218 commented on week6/Lv1_행렬의덧셈.ts
> +}
lodash 함수가 있었네요..!

2024-03-14 07:18 UTC, f-lab-jake requested changes

2024-03-14 07:18 UTC, f-lab-jake commented on week6/Lv1_행렬의덧셈.ts
>    );
`arrIdx`룰 안쓸수 없을까요?`zipWith`의 활용을 좀더 고민해보세요.

2024-03-16 04:51 UTC, f-lab-jake approved these changes

2024-04-01 22:29 UTC, ekdls1218 commented on week6/Lv1_행렬의덧셈.ts
>    );
넵 수정하였습니다!

2024-04-01 22:35 UTC, ekdls1218 commented on week6/Lv1_행렬의덧셈.ts
> +}
이중 배열이라서 처음`_zipWith()`은 같은 열의 배열을 결합해주고, 두번째 `_zipWith()`을 사용하여 결합한 배열의 같은 행의 숫자를 더해주었습니다

2024-04-02 02:01 UTC, f-lab-jake approved these changes

2024-04-02 02:01 UTC, f-lab-jake commented on week6/Lv1_행렬의덧셈.ts
>    );
저는 배열의 변수명을 `xs` `ys` `zs` 이런식으로 합니다. 원소는 `x` `y` `z`고요.
종종 별 의미없는 변수에 이름을 지어줘어ㅑ하는 경우가 있습니다. 그럴땐 짧게라도 쓰는게 낫다는 생각입니다.

2024-04-03 14:10 UTC, ekdls1218 commented on week6/Lv1_행렬의덧셈.ts
>    );
여기 배열도 변수 명이 의미가 중요하지 않으니 짧게 수정하는 것이 코드를 보기에 더 편할 것 같네요! 나중에 변수 명 지을 때도 참고하겠습니다 감사합니다:)

2024-04-04 00:40 UTC, f-lab-jake approved these changes

2024-04-05 13:18 UTC, f-lab-jake requested changes

2024-04-05 13:18 UTC, f-lab-jake commented on week6/Lv1_부족한금액계산하기.ts
> +  return money < totalPrice ? totalPrice - money : 0;
`Math.max`를 활용해보세요

2024-04-11 11:52 UTC, ekdls1218 commented on week6/Lv1_부족한금액계산하기.ts
> +  return money < totalPrice ? totalPrice - money : 0;
`Math.max`를 활용하여 비교해보았습니다! 그런데 저는 삼항연산자로 비교하는 것과 `Math.max`로 비교하는 것이 큰 차이가 없다고 느껴지는데 좀 더 간결해서 `Math.max`를 사용하는 걸까요??

2024-04-12 02:19 UTC, f-lab-jake approved these changes

2024-07-09 21:50 UTC, merged